### ISSUE TITLE
Resolve issues waking some cars from sleep

### ISSUE THREAD

**Issue by KipK** [OpenEVSE/openevse_esp32_firmware#512]
Some Zoe users needs to setup a special procedure to prevent the Zoe going in sleep state .
The /config set Sleep/Disable state for pause has been introduced for that.
But it doesn't seems to solve the issue on all Zoe.
They have a  start procedure on their smart home device to handle this:
- stop the car
- before it goes to sleep mode, plug the car and start a 30sec charge.
- set the EVSE to sleep ( 254 via $FS command)
This first procedure prevent the Zoe to go in sleep mode and not waking up later 
- when cheap rates  hours comes, put the EVSE to Disable ( 255 via $FD command) 
- wait few sec,
- Start charge ( $FE )

And then it seems to works.
The problem here is they still use RAPI commands for that, could be usefull to set an interface over the API to let them control that disabled state.

The /config one needs ESP32  to be restarted to let the disable state change effectively.

**Comment by KipK** [comment]
Yep  have a way to dynamically set over the api the disable state from 254 to 255 or vis versa without having to reboot EVSE & write to the flash nor using RAPI commands.

**Comment by mathieucarbou** [comment]
FYI I have a Zoe ZE50 E-Tech R110, and this vehicle is subject to the sleep issue.

Ref: https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/223
Ref: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/issues/643

So I added an automation in HA which is sending through mqtt a sequence of `$FD $FE` when vehicle connects. I don't need to start a charge.

```yaml
automation:
  # 
  - alias: "OpenEVSE: Zoé Bugfix"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.openevse_vehicle_connected
        from: "off"
        to: "on"
    condition: []
    action:
      - service: mqtt.publish
        data:
          topic: "openevse/rapi/in/$FD"
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: mqtt.publish
        data:
          topic: "openevse/rapi/in/$FE"
```

So far, and like reported in the issue in reference, this is pretty reliable.

I've seen this option in OpenEVSE:

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/61346/31cf6442-7437-4a11-b9ab-2ffedc714d43)

But I don't want to use it because of this warning:

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/61346/af8447b9-4277-44f3-a304-3c9a2c2c2d1a)

I am using EVSE with an HA integration. **I need and rely on the EVSE to be able to detect when a car is plugged.**, which is translated in mqtt with `vehicle = 0 or 1`.

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/61346/97bbe0f4-afa0-4ab0-85b8-eb89428d103e)

Considering RAPI through mqtt will be removed, I think we definitely need some mqtt topics to enable/disable EVSE.

I recently introduced `/restart` to restart the gateway.

Could we introduce something like  `/evse_enabled` and `/evse_enabled/set` set to `0` or `1` to be able to control that through mqtt ?

Thanks!
