### ISSUE TITLE
Remove RAPI

### ISSUE THREAD

**Issue by jeremypoulter** [OpenEVSE/openevse_esp32_firmware#643]
Since the switch to v4 and the move to have more of the smart features on the ESP32 RAPI it has always been the intention to remove or limit the user's ability to use RAPI: <https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/docs/rapi.md>

We now are in a place where the HTTP/MQTT APIs offers all the functions that RAPI can provide so I think the time has come to remove the RAPI commands from MQTT and limit the HTTP to RAPI gateway to just the `$Gx` for debugging.

Issues to resolve first

- [x] Missing API to reset EVSE module #479 / #618 
- [ ] Issues waking Zoes #512

**Comment by mathieucarbou** [comment]
I have a Zoe ZE50 E-Tech R110, and this vehicle is subject to the sleep issue.

Ref: https://github.com/OpenEVSE/ESP8266_WiFi_v2.x/issues/223

So I added an automation in HA which is sending through mqtt a sequence of `$FD $FE`:

```yaml
automation:
  # 
  - alias: "OpenEVSE: Zoé Bugfix"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.openevse_vehicle_connected
        from: "off"
        to: "on"
    condition: []
    action:
      - service: mqtt.publish
        data:
          topic: "openevse/rapi/in/$FD"
      - delay:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - service: mqtt.publish
        data:
          topic: "openevse/rapi/in/$FE"
```

So far, and like reported in the issue in reference, this is pretty reliable.

I've seen this option in OpenEVSE:

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/61346/31cf6442-7437-4a11-b9ab-2ffedc714d43)

But I don't want to use it because of this warning:

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/61346/af8447b9-4277-44f3-a304-3c9a2c2c2d1a)

I am using EVSE with an HA integration. **I need and rely on the EVSE to be able to detect when a car is plugged.**, which is translated in mqtt with `vehicle = 0 or 1`.

![image](https://github.com/OpenEVSE/ESP32_WiFi_V4.x/assets/61346/97bbe0f4-afa0-4ab0-85b8-eb89428d103e)

So if RAPI is removed, what are the options left to still be able to work around the sleep issue but still be able to detect when a car is plugged ?

Thanks!
