### ISSUE TITLE
[BUG] Solar Divert is closing and opening the contactor even is the car is not connected

### ISSUE THREAD

**Issue by mathieucarbou** [OpenEVSE/openevse_esp32_firmware#774]
```
OpenEVSE	8.2.3.EU	
OpenEVSE Wifi v5.0.2
```

My EV car is disconnected since 8:30 this morning.

Starting at ~ 10:15 to 11:20, we can see that I have enough solar production excess so the divert mode is allowing the charge, then is stopped allowing the charge, and again later.

The problem is that the EVSE is closing the contactor for nothing, because the EV car is not connected. This increases the wear of the contactor considerably. In a few month, because of this behaviour, I've reached 1114 swicthes. Just today, I got 8 more switches, while the car was disconnected.

I am using default parameters for divert:

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/61346/986c6923-b900-46a6-8a59-b5cee45d14dc)

I am closely monitoring the EVSE box from Home Assistant. Here is proof of what is happening. I can add more sensors if required.

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/61346/916135dd-b281-431e-9f76-773b1b2e82e0)

**Question**

What is the contactor closing and opening when the vehicule is disconnected ?

Thanks!

_Note 1: I've checked today and we actually ear the sound of the contactor switching._

_Note 2: today I was running with a smooth decay of 300 sec instead of 600 sec. Switched back to 600 sec juste now before the screenshot._

**Comment by mathieucarbou** [comment]
I have added an automation in HA to automatically switch solar divert on/off (and also set a claim) depending on the VE state

```yaml

  - alias: "OpenEVSE: Switch Soalr Divert"
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.openevse_vehicle_connected
    condition: []
    action:
      - if:
          - condition: state
            entity_id: binary_sensor.openevse_vehicle_connected
            state: "on"
        then:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.openevse_solar_divert
          - service: select.select_option
            data:
              option: Auto
            target:
              entity_id: select.openevse_charge_control
          - wait_template: "{{states.select.openevse_charge_control.state == 'Auto'}}"
            continue_on_timeout: true
          - service: select.select_option
            data:
              option: Allow Charge
            target:
              entity_id: select.openevse_charge_status
          - wait_template: "{{states.select.openevse_charge_status.state == 'Allow Charge'}}"
            continue_on_timeout: true
        else:
          - service: select.select_option
            data:
              option: Pause Charge
            target:
              entity_id: select.openevse_charge_status
          - wait_template: "{{states.select.openevse_charge_status.state == 'Pause Charge'}}"
            continue_on_timeout: true
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.openevse_solar_divert
```

VE connected:

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/61346/18fa36e1-75db-40ec-a7cb-f59612468ad6)

VE disconnected:

![image](https://github.com/OpenEVSE/openevse_esp32_firmware/assets/61346/9e50ec7b-dc11-4603-8589-df646d4a4ec7)

Ref: [OpenEVSE MQTT integration](https://gist.github.com/mathieucarbou/92a3d5e0dc38d6b68aa1bdaf153a80c5)
